version: '3.4'

services:
  wsei-aspnet_projekt:
    image: ${DOCKER_REGISTRY-}wseiaspnetprojekt
    build:
      context: .
      dockerfile: WSEI-aspnet_projekt/Dockerfile

  sqlserverService:  
    image: microsoft/mssql-server-linux:2017-latest  
    hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "cookbookpswd"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '1433:1433'  
    expose:  
      - 1433